# 1. Os parâmetros Lambda, DC, w, w_c e N já foram injetados pelo Python no Workspace!
# Vamos apenas definir as constantes caso não existam:
if (exist("height") == 0) { height = 0.22e-6; }
if (exist("material") == 0) { material = "Si (Silicon) - Palik"; }

# Cria Substrato inferior
addrect;
set("material", 'SiO2 (Glass) - Palik');
set("name","Substrato - SiO2");
set("x",0); set("x span", Lambda*8); set("y", 0); set("y span", w*3);
set("z", -0.22e-6); set("z span", 0.22e-6);

# Cria Substrato superior
addrect;
set("material", 'SiO2 (Glass) - Palik');
set("name","Substrato superior");
set("x",0); set("x span", Lambda*8); set("y", 0); set("y span", w*3);
set("z", 0); set("z span", height*3); set("alpha", 0.4);

# Cria guia anterior
addrect;
set("x min", -2*Lambda);
set("x max", -Lambda/2);
set("y", 0); set('y span', w);
set("z", -0.11e-6 + height/2); set('z span', height);
set("name", "Guide in");
set("material", material); set("alpha", 1);

# Cria o segmento do guia
addrect;
set("x min", -Lambda/2);
set("x max", -Lambda/2 + Lambda*DC);
set("y", 0); set('y span', w);
set("z", -0.11e-6 + height/2); set('z span', height);
set("name", "Segment period");
set("material", material);

# Cria o segmento do nucleo do guia
addrect;
set("x min", -Lambda/2 + Lambda*DC);
set("x max", Lambda/2);
set("y", 0); set('y span', w_c);
set("z", -0.11e-6 + height/2); set('z span', height);
set("name", "Segment core");
set("material", material);

# Cria guia posterior
addrect;
set("x min", Lambda/2);
set("x max", Lambda*2);
set("y", 0); set('y span', w);
set("z", -0.11e-6 + height/2); set('z span', height);
set("name", "Guide out");
set("material", material); set("alpha", 1);