# Configura o EME
addeme;

# set dimension
set("x min",-2*Lambda);
set("y",0);
set("y span",w*1.5);
set("z",0);
set("z span",height*3);

# set cell properties
select("EME");
set("display cells", 1);
set("number of cell groups",4);
set("group spans",[
                   (2*Lambda)-Lambda/2; 
                   Lambda*DC;            
                   Lambda*(1-DC);        
                   2*Lambda-Lambda/2     
                   ]);                  
set("cells",[1; 1; 1; 1]);
set("subcell method",[ 0; 0; 0; 0]);

# Define a seção periódica
set("number of periodic groups", 1);
set("start cell group", [2]);
set("end cell group",[3]);
set("periods", N);
 
# Propaga os modos nas células
run;

# (O emesweep será executado diretamente pelo script Python a seguir)